<a href="https://colab.research.google.com/github/25WH1A05AT/NASSCOM/blob/main/WEEK%202/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")


# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

arr1_1 = np.arange(100)
arr1_2 = np.ones((3, 3))
arr1_3 = np.full((2, 4), 7)
arr1_4 = np.random.randint(10, 51, (5, 5))

print("arr1_1:", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4:\n", arr1_4[:2])


# Task 2: Indexing and Slicing
print("\n--- Task 2: Indexing and Slicing ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

val2_1 = data[2, 3]
row2_2 = data[0, :]
col2_3 = data[:, 3]
sub_arr2_4 = data[1:3, 0:2]
filtered_elements2_5 = data[data > 100]

print("Element:", val2_1)
print("First row:", row2_2)
print("Last column:", col2_3)
print("Sub-array:\n", sub_arr2_4)
print("Greater than 100:", filtered_elements2_5)


# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("Original array:\n", arr3_1)
print("Modified array:\n", arr3_2)
print("Even count:", even_count3_3)


# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])

sum4_1 = np.sum(arr4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
max_rows4_3 = np.max(arr4_1, axis=1)
std4_4 = np.std(arr4_1)

print("Sum:", sum4_1)
print("Column means:", mean_cols4_2)
print("Row maximums:", max_rows4_3)
print("Standard deviation:", std4_4)


# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
flattened_arr5_4 = reshaped_arr5_2.flatten()
raveled_arr5_4 = reshaped_arr5_2.ravel()

print("4x6 array:\n", reshaped_arr5_2)
print("2x3x4 array:\n", reshaped_arr5_3)
print("Flattened:", flattened_arr5_4)
print("Raveled:", raveled_arr5_4)


# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10
vector = np.array([100, 200, 300])

result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("Scalar result:\n", result6_1)
print("Vector result:\n", result6_2)


# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("View:", view_arr7)
print("Original after view:", original_arr7)

copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Copy:", copy_arr7)
print("Original after copy:", original_arr7)


# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([
    [9, 10]
])

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

parts = np.array_split(combined_arr8_3, 3, axis=0)

part1 = parts[0]
part2 = parts[1]
part3 = parts[2]

print("Vertical stack:\n", vstack_arr8_1)
print("Horizontal stack:\n", hstack_arr8_2)
print("Combined array:\n", combined_arr8_3)
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2 = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])

sorted_arr9_1 = np.sort(arr9_1)
sorted_cols9_2 = np.sort(arr9_2, axis=0)
idx9_3 = np.where(arr9_1 == 9)[0]
max_idx9_4 = np.argmax(arr9_1)

print("Original array:", arr9_1)
print("Sorted array:", sorted_arr9_1)
print("Original 2D array:\n", arr9_2)
print("Sorted columns:\n", sorted_cols9_2)
print("Index of value 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)

--- Intermediate NumPy Exercise ---

--- Task 1: Array Creation Shortcuts ---
arr1_1: [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4:
 [[39 13 36 41 48]
 [21 32 23 27 25]]

--- Task 2: Indexing and Slicing ---
Element: 120
First row: [10 20 30 40]
Last column: [ 40  80 120 160]
Sub-array:
 [[ 50  60]
 [ 90 100]]
Greater than 100: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
Original array:
 [[ 5 14 15 17 19]
 [12  6 15 14 10]
 [13  2  3 16 19]
 [ 8 18  5  6  6]]
Modified array:
 [[ 0 14 15 17 19]
 [12  0 15 14 10]
 [13  0  0 16 19]
 [ 0 18  0  0  0]]
Even count: 11

--- Task 4: Aggregation Functions ---
Sum: 84
Column means: [11.          6.66666667 10.33333333]
Row maximums: [12 15 20]
Standard deviation: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---
4x6 array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2x3x4 array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]