<a href="https://colab.research.google.com/github/25WH1A05AT/NASSCOM/blob/main/WEEK%202/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

s1_1 = pd.Series([10, 20, 30, 40, 50])

np_array1_2 = np.random.randint(1, 101, size=(3, 4))

df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)

print("\nSeries:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)


# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

dates = pd.date_range(
    start='2023-01-01',
    end='2023-04-10',
    periods=100
)

df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(
        ['East', 'West', 'North', 'South'],
        size=100
    ),
    'Product': np.random.choice(
        ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        size=100
    ),
    'Sales': np.random.randint(
        100,
        1001,
        size=100
    ).astype(float),
    'Quantity': np.random.randint(
        1,
        11,
        size=100
    ).astype(float)
})

sales_nan_indices = np.random.choice(
    df_sales.index,
    size=5,
    replace=False
)

quantity_nan_indices = np.random.choice(
    df_sales.index,
    size=3,
    replace=False
)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print("\nSales DataFrame:")
print(df_sales.head(10))

print("\nDataFrame shape:")
print(df_sales.shape)


# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

df3_1 = df_sales[['Region', 'Sales']]

df3_2 = df_sales[
    df_sales['Product'] == 'Laptop'
]

df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

monitor_rows = df_sales[
    df_sales['Product'] == 'Monitor'
]

if not monitor_rows.empty:
    monitor_position = monitor_rows.index[0]
    val3_4 = df_sales.loc[monitor_position, 'Sales']
    val3_4_iloc = df_sales.iloc[
        df_sales.index.get_loc(monitor_position)
    ]['Sales']
else:
    val3_4 = np.nan
    val3_4_iloc = np.nan

print("\nRegion and Sales:")
print(df3_1.head())

print("\nLaptop rows:")
print(df3_2.head())

print("\nEast region with Sales > 500:")
print(df3_3.head())

print("\nFirst Monitor Sales using loc:", val3_4)
print("First Monitor Sales using iloc:", val3_4_iloc)


# Task 4: Data Cleaning
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

missing_counts4_1 = df_sales.isna().sum()

df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = (
    df4_2_filled['Sales'].fillna(sales_mean)
)

df4_3_dropped = df_sales.dropna()

print("\nMissing values:")
print(missing_counts4_1)

print("\nDataFrame after filling Sales:")
print(df4_2_filled.head())

print("\nDataFrame after dropping missing rows:")
print(df4_3_dropped.head())

print("\nRows after dropping missing values:")
print(len(df4_3_dropped))


# Task 5: Data Manipulation
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

df_sales['Total_Revenue'] = (
    df_sales['Sales'] *
    df_sales['Quantity']
)

df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

df5_3_grouped_region = (
    df_sales
    .groupby('Region')[['Sales', 'Quantity']]
    .sum()
)

df5_4_grouped_product = (
    df_sales
    .groupby('Product')['Sales']
    .mean()
    .to_frame(name='Average_Sales')
)

print("\nDataFrame with Total Revenue:")
print(df_sales.head())

print("\nSorted DataFrame:")
print(df5_2_sorted.head())

print("\nSales and Quantity by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)




--- Intermediate Pandas Exercise ---

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[31 91  4 68]
 [17 55 42 75]
 [17 98 49 70]]

DataFrame:
    A   B   C   D
0  31  91   4  68
1  17  55  42  75
2  17  98  49  70

--- Task 2: Synthetic Data Generation for Practice ---

Sales DataFrame:
        Date Region   Product  Sales  Quantity
0 2023-01-01  North    Laptop    NaN       7.0
1 2023-01-02  South    Laptop  328.0      10.0
2 2023-01-03   West    Laptop  114.0       6.0
3 2023-01-04  South    Laptop  204.0       5.0
4 2023-01-05   West   Monitor  314.0       1.0
5 2023-01-06  South  Keyboard  450.0       8.0
6 2023-01-07   West     Mouse  552.0       4.0
7 2023-01-08  North  Keyboard  571.0       6.0
8 2023-01-09  North    Laptop  626.0       5.0
9 2023-01-10   West  Keyboard  342.0       8.0

DataFrame shape:
(100, 5)

--- Task 3: Indexing and Slicing in DataFrames ---

Region and